// Generated by CoffeeScript 1.4.0
(function() {

  window.FooController = function($scope) {
    console.log('Init FooController');
    $scope.foo = {
      bar: 'Example Text'
    };
  };

  window.FooController.$inject = ['$scope'];

}).call(this);
